Update symbol
bitzenyPlus/BitZenyPlus pull request #19
Opened 2018-08-05 19:21 UTC by bellflower2015

#8 
![screen shot 2018-08-06 at 4 37 09](https://user-images.githubusercontent.com/12813420/43689307-8643c186-9933-11e8-8967-56696c42e02d.png)
![screen shot 2018-08-06 at 4 37 30](https://user-images.githubusercontent.com/12813420/43689309-929a996e-9933-11e8-9d0c-dbb42ca1cdde.png)
![screen shot 2018-08-06 at 4 37 48](https://user-images.githubusercontent.com/12813420/43689310-9673559e-9933-11e8-97de-c7672a4805aa.png)
![screen shot 2018-08-06 at 4 38 16](https://user-images.githubusercontent.com/12813420/43689313-a0ec4a3a-9933-11e8-92a6-1e5171f06db9.png)
![screen shot 2018-08-06 at 4 50 05](https://user-images.githubusercontent.com/12813420/43689363-50412fb4-9934-11e8-9753-2f02cb509128.png)
![screen shot 2018-08-06 at 4 38 40](https://user-images.githubusercontent.com/12813420/43689317-a8e662de-9933-11e8-89f2-7ca68eb9bf7e.png)
![screen shot 2018-08-06 at 4 39 02](https://user-images.githubusercontent.com/12813420/43689320-acd047fc-9933-11e8-8633-73a17b0f8c8e.png)
![screen shot 2018-08-06 at 4 39 11](https://user-images.githubusercontent.com/12813420/43689321-af45770a-9933-11e8-956d-e8e58d471526.png)

2018-08-05 19:33 UTC, cryptozeny commented
plz add the issue number for tracking ;)

https://github.com/bitzenyPlus/BitZenyPlus/issues/8

2018-08-05 20:03 UTC, cryptozeny requested changes
![screenshot from 2018-08-06 05-06-36](https://user-images.githubusercontent.com/37016180/43689518-be8d6544-9936-11e8-802a-43acb94bdcca.png)


余白(margin)やアイコンサイズがビットコインと違うのに、少し減らすのがどうですか? :sweat_smile: 

original btc
![bitcoin](https://user-images.githubusercontent.com/37016180/43689432-a2759198-9935-11e8-837a-2c2c6fee48e7.png)

zny
![bitcoin](https://user-images.githubusercontent.com/37016180/43689451-e44d0718-9935-11e8-850e-7a29ef9d75e4.png)

the size is different...?

BTC
https://github.com/bitcoin/bitcoin/blob/master/src/qt/res/icons/bitcoin.png

ZNY
https://github.com/bitzenyPlus/BitZenyPlus/blob/feature/symbol/src/qt/res/icons/bitcoin.png

2018-08-05 20:16 UTC, bellflower2015 commented
画像の大きさは `z2.0.x` のファイルと同じです。
bitcoinのものとは異なります。

2018-08-05 20:28 UTC, cryptozeny commented
> 画像の大きさは z2.0.x のファイルと同じです。
bitcoinのものとは異なります。

あ、ほんとうですか? ところが、マージンが変わってくるから何か太って見えるが…

![screenshot from 2018-08-06 05-27-43](https://user-images.githubusercontent.com/37016180/43689714-84834c6c-9939-11e8-8e7c-c697200323d0.png)

splash screenで解像度が落ちて見られる。

2018-08-05 20:46 UTC, bellflower2015 commented
`z2.0.x` が間違っていたのかもしれないですね。
`src/qt/icons/bitcoin.png` が小さすぎるようです。

2018-08-05 20:53 UTC, bellflower2015 commented
![screen shot 2018-08-06 at 5 49 18](https://user-images.githubusercontent.com/12813420/43689959-f9d54bf2-993c-11e8-9b49-4080b3c087c1.png)

2018-08-05 20:58 UTC, cryptozeny commented
splash screenはなっているようです。 もしaboutのアイコンmarginも調節できるでしょうか?

2018-08-05 21:13 UTC, bellflower2015 commented
画像の余白なので、調節不可です。

2018-08-05 21:18 UTC, cryptozeny commented
![screenshot from 2018-08-06 06-17-43](https://user-images.githubusercontent.com/37016180/43690166-74af86a0-9940-11e8-9996-482ca19f39bd.png)
![screenshot from 2018-08-06 06-16-10](https://user-images.githubusercontent.com/37016180/43690167-77301e4e-9940-11e8-9704-e871d6f8290f.png)



BTCには余白があって、ZNYにはない。 余白を作ればならないか?

2018-08-05 21:19 UTC, bellflower2015 commented
余白を作ると、他の表示にも影響します。
aboutだけ対応したければ、別のファイルを作成しなければならない。
対応しなくていいと思います。

2018-08-05 21:21 UTC, cryptozeny commented
https://github.com/bitcoin/bitcoin/blob/master/src/qt/res/icons/bitcoin.ico

this `ico` file right?

2018-08-05 21:23 UTC, bellflower2015 commented
~~はい。そのファイルです。~~
失礼、`src/qt/res/icons/bitcoin.png`でした。PNGです。
変更すれば、他にも影響します。
例えば、splashにも同様に余白が付きます。

2018-08-05 21:24 UTC, cryptozeny commented
![screenshot from 2018-08-06 06-23-17](https://user-images.githubusercontent.com/37016180/43690213-46e45f24-9941-11e8-8321-64e182ed98b9.png)

ライトコインも余白があるようだ。 標準規格に合わせたほうがいいんじゃないですか。

2018-08-05 21:26 UTC, bellflower2015 commented
少し小さくしてみましょうか。

2018-08-05 21:26 UTC, cryptozeny commented
![screenshot from 2018-08-06 06-26-01](https://user-images.githubusercontent.com/37016180/43690226-a133e65c-9941-11e8-8a8f-5c48961d97bc.png)

monacoin too

2018-08-05 21:27 UTC, cryptozeny commented
先に他のコインが使用する標準規格と余白のサイズを調査しなければならない。

2018-08-05 21:30 UTC, cryptozeny commented
~~splash >> `bitcoin.png`~~
~~about >> `bitcoin.ico`~~

~~二つが他派の日です。~~

added:
i was wrong

2018-08-05 21:33 UTC, bellflower2015 commented
いいえ、splashもaboutも`bitcoin.png`です。

2018-08-05 21:37 UTC, cryptozeny commented
そうなんですね もっと調べてみます。

2018-08-05 21:37 UTC, cryptozeny commented
余白を入れるとどんな問題が生じますか? 他のコインは問題がないようだが... :thinking:

2018-08-05 21:38 UTC, bellflower2015 commented
![screen shot 2018-08-06 at 6 32 20](https://user-images.githubusercontent.com/12813420/43690327-43065126-9943-11e8-8f60-2e3fba57ff8b.png)
![screen shot 2018-08-06 at 6 34 05](https://user-images.githubusercontent.com/12813420/43690329-48bcc4f6-9943-11e8-92e0-d5e1b4aa2f57.png)

2018-08-05 21:40 UTC, cryptozeny commented
splashはよく分からないけど、aboutは確かにいいです!

2018-08-05 21:43 UTC, bellflower2015 commented
`bitcoin.png`だけの変更ですが、splashも影響します。
良さそうですね。😊

2018-08-05 21:44 UTC, cryptozeny commented
寝て起きて再び確認します。 眠くて美的感覚が落ちました。

2018-08-06 09:07 UTC, hitobb commented
複数のシンボルマークを用意しています。都合の良いものを選んでください。

https://github.com/bitzenyPlus/symbol_mark

AIファイルもあるので、イラストレータがあれば編集可能です。
完成したファイルをあとからgithubにアップロードしませんか？

2018-08-06 09:18 UTC, bellflower2015 commented
@hitobb 
そこから選んで使ってるし、余白調整しただけだし
画像データそのものはコミットログみればわかるよ
余白調整版のPNG(`src/qt/res/icons/bitcoin.png`)はマージ完了したらあちらにもコミットしましょうか

2018-08-06 09:26 UTC, cryptozeny commented
![menu_116](https://user-images.githubusercontent.com/37016180/43708739-1add5a9c-99a6-11e8-9ce8-893a83a6c1ee.png)
![about bitzeny core_114](https://user-images.githubusercontent.com/37016180/43708740-1b21c074-99a6-11e8-96f6-7fcf2b66c568.png)
![bitzeny core _113](https://user-images.githubusercontent.com/37016180/43708741-1b4a3c20-99a6-11e8-9b79-2de143391034.png)

it's good, but on unity panel i don't see well...

![screenshot from 2018-08-06 18-24-25](https://user-images.githubusercontent.com/37016180/43708809-40f2d522-99a6-11e8-9a80-33007ef55027.png)

2018-08-06 09:54 UTC, bellflower2015 commented
@cryptozeny 
unity panelについて：
暗い背景だと見づらい。
明るい背景だと見やすい。
あらゆる環境で見やすいアイコンにするのは、難しい。
デザイナーに何度も発注するのも困る。
妥協するか、または、妥協しないならば、しっかり考えて決めなければならない。

2018-08-06 12:18 UTC, zinntikumugai commented
@cryptozeny @bellflower2015 
Discordのリアクションのように少し加工するのはどうですか？
![img](https://i.gyazo.com/ef6a3e10361a91258f0ed5f51fa15427.png)
左：オリジナル
右：白埋め
(サンプルが非常に見づらい)

2018-08-06 12:23 UTC, cryptozeny commented
like this? 

`mono` VS `mono dark`

![screenshot from 2018-08-06 21-22-13](https://user-images.githubusercontent.com/37016180/43716371-e581529a-99be-11e8-9169-5b818e2d97cc.png)

it can be convert easily, but we have to ask to the designer...

2018-08-06 12:25 UTC, cryptozeny commented
@zinntikumugai 

![screenshot from 2018-08-06 21-24-27](https://user-images.githubusercontent.com/37016180/43716450-22cdb224-99bf-11e8-821e-a32952e20287.png)

this is simple solution, but i don't think it's right one...

2018-08-06 12:28 UTC, zinntikumugai commented
@cryptozeny 
この画像が正しいとは思えないのは同感です
しかし、オリジナルを使うと大変見づらい

2018-08-06 13:14 UTC, zinntikumugai commented
Discordサーバーのリアクションを採用する際にあまりにもDiscordのダークテーマに同化するため、私がオリジナルシンボルを多少いじったものです
![img](https://i.imgur.com/Y7aws4b.png)
![img](https://i.imgur.com/0OLdS6I.png)
![img](https://i.imgur.com/kaaYisV.png)
![img](https://i.imgur.com/eikG27t.png)
![img](https://i.imgur.com/Mvdmwj3.png)
![img](https://i.imgur.com/gfx5RqC.png)
![img](https://i.imgur.com/60Uh0VP.png)

2018-08-06 13:24 UTC, cryptozeny commented
i think this looks ok for `mono dark theme`, but a little strange gradations? could you more test this icon on dark theme? @zinntikumugai 

![68747470733a2f2f692e696d6775722e636f6d2f65696b473237742e706e67](https://user-images.githubusercontent.com/37016180/43719003-6c0fd450-99c7-11e8-83ae-a24b9aeeb5c3.png)

2018-08-06 13:40 UTC, zinntikumugai commented
@cryptozeny 
そのアイコンはオリジナルを白黒反転したものです

2018-08-06 13:52 UTC, bellflower2015 commented
アイコンの問題のみ、 #22 暗い背景でアイコンが見づらい問題 に別Issueとして立てました。
この問題を除き、他がOKならば、レビュー承認してください。

2018-08-06 14:53 UTC, cryptozeny approved these changes
ok however we have to do more things later

#24 #22 #8

2018-08-06 15:10 UTC, merged